language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

install:
- npm install

script:
- npm run build
- openssl aes-256-cbc -K $encrypted_6c022d3a0baa_key -iv $encrypted_6c022d3a0baa_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- git config user.name "Automatic Publish"
- git config user.email "RRMoelker@users.noreply.github.com"
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; node ./scripts/deploy-gh-pages.js
